// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlMonitor.Api.Data;

#nullable disable

namespace UrlMonitor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613020534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("UrlMonitor.Api.Models.HealthCheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MonitoredUrlId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredUrlId", "Timestamp")
                        .HasDatabaseName("IX_HealthCheckResult_MonitoredUrlId_Timestamp");

                    b.ToTable("HealthCheckResults");
                });

            modelBuilder.Entity("UrlMonitor.Api.Models.MonitoredUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonitoredUrls");
                });

            modelBuilder.Entity("UrlMonitor.Api.Models.HealthCheckResult", b =>
                {
                    b.HasOne("UrlMonitor.Api.Models.MonitoredUrl", "MonitoredUrl")
                        .WithMany("Results")
                        .HasForeignKey("MonitoredUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredUrl");
                });

            modelBuilder.Entity("UrlMonitor.Api.Models.MonitoredUrl", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
